name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        source: "DbSeed.json"
        target: "DbSeed.json/Configurations"
    - name: Test
      run: dotnet test --no-build --verbosity normal
