name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Printing
      run: |
        echo "All:"
        echo "${{ steps.abc.outputs.all }}"
        echo "Added:"
        echo "${{ steps.abc.outputs.added }}"
        echo "Removed:"
        echo "${{ steps.abc.outputs.removed }}"
        echo "Renamed:"
        echo "${{ steps.abc.outputs.renamed }}"
        echo "Modified:"
        echo "${{ steps.abc.outputs.modified }}"
        echo "Added+Modified:"
        echo "${{ steps.abc.outputs.added_modified }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal
