name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Copy file
      run: |
        mkdir -p ./tests/GSalvi.EventSourcing.MongoDb.IntegrationTests/bin/Debug/net5.0/Configurations
        cp ./tests/GSalvi.EventSourcing.MongoDb.IntegrationTests/Configurations/DbSeed.json ./tests/GSalvi.EventSourcing.MongoDb.IntegrationTests/bin/Debug/net5.0/Configurations/
        cp ./tests/GSalvi.EventSourcing.MongoDb.IntegrationTests/Configurations/appsettings.json ./tests/GSalvi.EventSourcing.MongoDb.IntegrationTests/bin/Debug/net5.0/Configurations/
        ls -R
    - name: Test
      run: dotnet test --no-build --verbosity normal
